### ISSUE TITLE
get_version module

### ISSUE THREAD

**Issue by apaliwal90** [bsungwoo/spSeudoMap#2]
Hi there, 

Thank you for this work! I am hoping to use it on some of my own data, but I am running into some trouble with the get-version module. It seems that there is not a version that is compatible with Python 3.7, specified by the conda environment. It seems like it is unable to detect the version control system properly. Do you have any advice on how I can work around this error? 

TypeError: _detect_vcs() missing 2 required positional arguments: 'expected_vcs' and 'path'

Thanks for your help!

**Comment by bsungwoo** [comment]
@apaliwal90 Sorry for the late reply. I am planning to update the code to Python 3.8 very soon. Could you just wait a while?

**Comment by bsungwoo** [comment]
@apaliwal90 We have updated the package to work in Python 3.8 and TensorFlow 2.X and the bug seems to be fixed.
